### ISSUE TITLE
Resistor Color Duo Experiment

### ISSUE THREAD

**Issue by iHiD** [exercism/javascript-analyzer#49] opened 2019-09-23 23:37 UTC
Please leave comments below regarding this experimental output.

**Comment by SleeplessByte** [comment] 2019-09-26 16:45
Open issues:

#50 
#55 
#56 
#57

**Comment by JimLynchCodes** [comment] 2020-06-07 23:12
analyzer feedback

"The student is using parseFloat or parseInt to convert back to a number. Perhaps they need an introduction to or reminder of Number(...). The parseXXX family is great if you do not know if the input is a number, but when you know it, it's better to use the stricter Number(...) function."

it would be nice imo if it explained a bit _why_ number is better. Perhaps it could say "faster" rather than "better"?

**Comment by pertrai1** [comment] 2021-02-22 06:42
I don't see `resistor-color-trio`. Has this been removed or am I missing where to find it?

**Comment by SleeplessByte** [comment] 2021-02-22 12:44
@pertrai1 we don't have analyzer implementation of `resistor-color-trio` (yet). Is that what you're looking for? Or are you looking for the exercise in the first place?

**Comment by SleeplessByte** [comment] 2021-02-23 23:18
Yes. Resistor-color-trio is an exercise that we might not have implemented. The best repo to request it would be Exercism/JavaScript.

**Comment by bobahop** [comment] 2021-05-05 13:30
If they import their `Resistor Color` solution and use it I certainly point out it's a good thing. But I don't disapprove if they treat the solution on its own. As someone who copies and pastes the source code, multi-file solutions are a hassle for me and I usually avoid them.

**Comment by peterschussheim** [comment] 2021-05-28 14:33
Two issues I think would be useful for the auto analyzer to catch:

1. an incorrect case of the elements in the `COLORS` array. ex: `"Red"` vs `"red"`
2. unnecessary export of the `COLORS` array.

**Comment by SleeplessByte** [comment] 2021-05-29 07:19
@peterschussheim are either of those "non idiomatic" usage of the Language? 

I'm looking for the advice we would give on both those instances. For example we might want to recommend only break the module boundary when absolutely necessary (exporting the colours).

**Comment by Marmadukethe1st** [comment] 2021-07-03 08:42
"Recommendation: Disapprove with comments

Mentor the student to add helper function and DRY-up this solution. The solution to resistor-color can be used as helper method here. When using an Array as colors source, in a years time, will the student recall why it's the index in that array? When using an Object, what does the value mean?
Re-using colorCode explains this in both cases.

Try suggesting the following:

Using a helper method is good practice, because it replaces a cryptic "member call" with a named call that can be documented individually."

To me this seems contradictory to the advise in the Mentor notes which says:

"Importing resistor-color

A student may import their colorCode function from ../resistor-color/resistor-color. This is perfectly fine and should be regarded as such. DO NOT suggest them to add this import if they don't have it."

**Comment by SleeplessByte** [comment] 2021-07-03 20:16
@marmadukethe1st it's hard to see what are comments and what are not, even though you've added `""`. You can use `>` to indicate a quote:

```markdown
> Recommendation: Disapprove with comments
> 
> Mentor the student to add helper function and DRY-up this solution. The solution to resistor-color can be used as helper method here. When using an Array as colors source, in a years time, will the student recall why it's the index in that array? When using an Object, what does the value mean?
Re-using colorCode explains this in both cases.
> 
> Try suggesting the following:
> 
> Using a helper method is good practice, because it replaces a cryptic "member call" with a named call that can be documented individually.

To me this seems contradictory to the advise in the Mentor notes which says:

> Importing resistor-color
> 
> A student may import their colorCode function from ../resistor-color/resistor-color. This is perfectly fine and should be regarded as such. DO NOT suggest them to add this import if they don't have it."
```

Can you explain why it seems to be contradictory? Importing the helper function from a different module/file isn't contradictory with "having a helper function". 

However, the _goal_ of the exercise is not to re-use a previously written module, which is why we don't suggest to import it from a different place.

**Comment by Marmadukethe1st** [comment] 2021-07-04 11:12
Thanks I'll keep that in mind.

The exercise suggested Disapprove with comments because the iteration didn't include the import.

Yet the notes suggest you shouldn't Disapprove because of the lack of an import.

Maybe I'm not reading it correctly.

Sent from Samsung Mobile on O2
Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by SleeplessByte** [comment] 2021-07-05 17:13
I understand you better now :)

It suggest to disapprove with comments because there is no _helper_ function. That _helper_ function may be:

- written in `resistor-color-duo.js`
- imported from `resistor-color.js`

The notes mention that importing is fine. 

Here are a few examples based on those two comments:

## Good

```javascript
// Written in the same file
function colorCode(name) {
  return COLORS.indexOf(name)
}

function value([tens, ones]) {
  return colorCode(tens) * 10 + colorCode(ones)
}

// const COLORS = ...
```

## Good

```javascript
// Written in the same file
import { colorCode } from '../resistor-color/resistor-color'

function value([tens, ones]) {
  return colorCode(tens) * 10 + colorCode(ones)
}

// const COLORS = ..
```

## Could be improved

```javascript
function value([tens, ones]) {
  return COLORS.indexOf(tens) * 10 + COLORS.indexOf(ones)
}

// const COLORS = ...
```

**Comment by SleeplessByte** [comment] 2021-09-04 15:47
Closing this because it's no longer experiemental.

**Closed by SleeplessByte** 2021-09-04 15:47 UTC

**Comment by simbabque** [comment] 2023-01-23 22:40
I just found this by googling the _Using a helper method is good practice, because it replaces a cryptic "member call" with a named call that can be documented individually_ message, which the automatic code analysis showed me. I was very confused about what the analyser wanted from me. That helper is a function, not a method. There's no class in my code, so it can't be a method. I thought it was talking about `Array.indexOf()`, but my solution had an object, so that made little sense. I think the wording of that advice is unlucky.

**Comment by SleeplessByte** [comment] 2023-01-24 03:14
@simbabque yeah, it used to be a `class`. This would be a good thing to PR in the `website-copy` repo.

Can you post your solution here and tag me? Then I can look why it's telling you what it's telling.

**Comment by simbabque** [comment] 2023-01-24 10:31
Thanks for getting back to me.

So the first iteration I had is as follows. I couldn't figure out how to link to it, so here it is verbatim.

```js
const codes = {
  black: 0,
  brown: 1,
  red: 2,
  orange: 3,
  yellow: 4,
  green: 5,
  blue: 6,
  violet: 7,
  grey: 8,
  white: 9
};
export const decodedValue = ([first, second]) => {
  return codes[first] * 10 + codes[second];
};
```

This clearly doesn't use a helper, and I suppose the analyser has looked for the array member syntax in `decodedValue`.

I then changed it to still use the object, but have a second function as a helper after reading this thread.

```js
const codes = {
  black: 0,
  brown: 1,
  red: 2,
  orange: 3,
  yellow: 4,
  green: 5,
  blue: 6,
  violet: 7,
  grey: 8,
  white: 9
};
const decode = (color) => {
  return codes[color];
};
export const decodedValue = ([first, second]) => {
  return decode(first) * 10 + decode(second);
};
```

The analyser now still finds an issue, but it doesn't tell me what the issue is. Here's a screenshot. I tried to reload the page a few times, but this is consistent. It doesn't have a message.

![image](https://user-images.githubusercontent.com/1125067/214268353-91841b75-1517-44c5-a92f-cc1f15d417ad.png)

**Comment by SleeplessByte** [comment] 2023-01-24 18:53
> The analyser now still finds an issue, but it doesn't tell me what the issue is. Here's a screenshot. I tried to reload the page a few times, but this is consistent. It doesn't have a message.

It's because it's trying to show you a message:

```json
{
  "comments": [
    {
      "comment": "javascript.resistor-color-duo.must_optimise_helper",
      "params": {
        "method.name": "decode"
      },
      "type": "actionable"
    }
  ]
}
```

But this message is commentary for mentors: https://github.com/exercism/website-copy/blob/main/analyzer-comments/javascript/resistor-color-duo/commentary/must_optimise_helper.md, and thus incorrectly linked. It's trying to show you this because it doesn't recognize that using an `Object` here results in that particular helper. It expected the `COLORS` constant to be an array.

You can ignore it.
